# Indexing in NumPy
Indexing can be used to find the position of the elements in an array.

In [1]:
import numpy as np
a=np.array([2,4,6,8,3,1,9])
print(a)

[2 4 6 8 3 1 9]


# Indexing for 1-D array:

# Positive Indexing:

In [2]:
print(a[0])

2


In [3]:
print(a[2])

6


In [4]:
print(a[6])

9


In [5]:
print(a[1])

4


# Negative Indexing:

In [6]:
print(a[-1])

9


In [7]:
print(a[-4])

8


In [8]:
print(a[-7])

2


# Indexing for 2-D array:

# Positive Indexing:

In [16]:
import numpy as np
b = np.array([[20,40,60],[10,30,50]])
print(b)

[[20 40 60]
 [10 30 50]]


In [17]:
print(b[0,1])

40


In [18]:
print(b[0,2])

60


In [19]:
print(b[1,1])

30


In [20]:
print(b[1,0])

10


In [21]:
print(b[1,2])

50


# Indexing for 3-D array:

# Positive Indexing:

In [22]:
import numpy as np
c = np.array([[[10,40,80],[20,60,70]],[[30,50,90],[25,63,79]]])
print(c)

[[[10 40 80]
  [20 60 70]]

 [[30 50 90]
  [25 63 79]]]


In [23]:
print(c[0,0,2])

80


In [24]:
print(c[1,0,1])

50


In [25]:
print(c[0,1,0])

20


In [26]:
print(c[1,1,2])

79


In [27]:
print(c[1,1,1])

63


In [28]:
print(c[0,0,1])

40


In [29]:
print(c[1,0,2])

90


In [30]:
print(c[-1,-1,-1])

79


# Slicing in NUmPy

slicing can be used to extract some portion of elements.

[Start Index:Stop Index:Step Size]

start Index - By default - zero(0)

stop Index - By DEfault - length of array

step size - By Default - one(1)

start index includes
stop index excludes

# Slicing of 1-D array:

In [2]:
import numpy as np
d = np.array([25,35,45,55,65,75])
print(d)

[25 35 45 55 65 75]


In [3]:
print("25 to 75:",d[0:6:1])

25 to 75: [25 35 45 55 65 75]


In [4]:
print("45 to 65:",d[2:5])

45 to 65: [45 55 65]


In [40]:
print(d[2:5:2])

[45 65]


In [41]:
print(d[1:4])

[35 45 55]


In [42]:
print(d[0:6:2])

[25 45 65]


In [5]:
print(d[:])

[25 35 45 55 65 75]


In [7]:
print(d[0:])

[25 35 45 55 65 75]


In [8]:
print(d[2:])

[45 55 65 75]


# Slicing of 2-D array:

# Slicing:[row-lower:row-upper, col-lower:col-upper]

In [43]:
import numpy as np
e = np.array([[10,30,50],[60,70,80]])
print(e)

[[10 30 50]
 [60 70 80]]


In [45]:
print(e[0,0:3])

[10 30 50]


In [46]:
print(e[1,1:3])

[70 80]


In [47]:
print(e[0:2,0:2])

[[10 30]
 [60 70]]


In [49]:
import numpy as np
f = np.array([[10,30,50,60],[90,70,80,20]])
print(f)

[[10 30 50 60]
 [90 70 80 20]]


In [55]:
print(f[0:4:2,0])

[10]


In [56]:
print(f[1,1:4])

[70 80 20]


In [58]:
print(f[0,1:3])

[30 50]


In [59]:
print(f[1,1:2])

[70]


In [10]:
import numpy as np
l = [[20,40,60],[10,30,50],[70,80,90]]
arr=np.array(l)
print(arr)

[[20 40 60]
 [10 30 50]
 [70 80 90]]


In [15]:
arr_1 = arr[0:3, 0:3]
print(arr_1)

[[20 40 60]
 [10 30 50]
 [70 80 90]]


In [5]:
arr_2 = arr[0:2, 0:3]
print(arr_2)

[[20 40 60]
 [10 30 50]]


In [6]:
arr_3 = arr[0:3, 0:2]
print(arr_3)

[[20 40]
 [10 30]
 [70 80]]


In [7]:
arr_4 = arr[1:3, 1:3]
print(arr_4)

[[30 50]
 [80 90]]


In [9]:
arr_5 = arr[:,:]
print(arr_5)

[[20 40 60]
 [10 30 50]
 [70 80 90]]


In [11]:
arr_6 = arr[1,1:]
print(arr_6)

[30 50]


In [12]:
arr_7 = arr[2,1:]
print(arr_7)

[80 90]


In [16]:
arr_8 = arr[0:3:2, 0:3:2]
print(arr_8)

[[20 60]
 [70 90]]


In [18]:
arr_9 = arr[0:3:, 0:3:2]
print(arr_9)

[[20 60]
 [10 50]
 [70 90]]


In [19]:
arr_10 = arr[0:3:, 0:3:]
print(arr_10)

[[20 40 60]
 [10 30 50]
 [70 80 90]]


# Slicing of 3-D array:

In [60]:
import numpy as np
g = np.array([[[20,40,60,80],[43,76,89,74]],[[23,84,29,75],[19,63,27,92]]])
print(g)

[[[20 40 60 80]
  [43 76 89 74]]

 [[23 84 29 75]
  [19 63 27 92]]]


In [61]:
print(g[0,0,0:4])

[20 40 60 80]


In [62]:
print(g[0,1,1:4])

[76 89 74]


In [63]:
print(g[0,0,1:2])

[40]


In [64]:
print(g[0,1,1:3])

[76 89]


In [65]:
print(g[0,1,0:3])

[43 76 89]


In [66]:
print(g[1,1,1:4])

[63 27 92]


In [67]:
print(g[1,0,0:3])

[23 84 29]


In [68]:
print(g[1,1,1])

63


In [69]:
print(g[0,0,1])

40


In [70]:
print(g[1,1,1:2])

[63]


In [72]:
print(g[0,0])

[20 40 60 80]


In [73]:
print(g[1,1])

[19 63 27 92]


In [75]:
print(g[0,1])

[43 76 89 74]


In [76]:
print(g[0,1,0:4])

[43 76 89 74]


In [80]:
print(g[0:2,0:2,0:2])

[[[20 40]
  [43 76]]

 [[23 84]
  [19 63]]]


In [10]:
import numpy as np
l2 = [20,40,60,80,100]
arr_6 = np.array(l2)
print("Elements:")
for ele in arr_6:
    print(ele)

Elements:
20
40
60
80
100


# Iterating NumPy Arrays

In [13]:
import numpy as np
l3 = [[20,40,60],[80,100,120],[140,160,180]]
arr_7 = np.array(l3)
print("Elements:")
for ele in arr_7:
    print(ele)

Elements:
[20 40 60]
[ 80 100 120]
[140 160 180]


In [19]:
import numpy as np
l4 = [[20,40,60],[80,100,120],[140,160,180]]
arr_8 = np.array(l4)
print("Elements:")
for row in arr_8:
    for ele in row:
        print(ele)

Elements:
20
40
60
80
100
120
140
160
180


In [21]:
import numpy as np
l4 = [[20,40,60],[80,100,120],[140,160,180]]
arr_8 = np.array(l4)
print("Elements:")
for row in arr_8:
    for ele in row:
        print(ele)
    print(ele,end=" ")
print()

Elements:
20
40
60
60 80
100
120
120 140
160
180
180 


In [21]:
import numpy as np
ar1 = [23,34,45,56,67,78,89]
print(ar1)
print()
for i in ar1:
    print(i)

[23, 34, 45, 56, 67, 78, 89]

23
34
45
56
67
78
89


In [24]:
import numpy as np
ar2 = [23,34,45,56,67,78],[12,24,36,48,52,60]
print(ar2)
print()
for i in ar2:
    for j in i:
        print(j)

([23, 34, 45, 56, 67, 78], [12, 24, 36, 48, 52, 60])

23
34
45
56
67
78
12
24
36
48
52
60


In [26]:
import numpy as np
ar3 = [[[23,34,45,56,67,78],[12,24,36,48,52,60]]]
print(ar3)
print()
for i in ar3:
    for j in i:
        for k in j:
            print(k)

[[[23, 34, 45, 56, 67, 78], [12, 24, 36, 48, 52, 60]]]

23
34
45
56
67
78
12
24
36
48
52
60


#   or

In [28]:
ar4 =np.array([[[23,34,45,56,67,78],[12,24,36,48,52,60]]])
print(ar4)
print(ar4.ndim)
print()
for i in np.nditer(ar4):
    print(i)

[[[23 34 45 56 67 78]
  [12 24 36 48 52 60]]]
3

23
34
45
56
67
78
12
24
36
48
52
60


In [32]:
ar5=np.array([[[23,34,45,56,67,78],[12,24,36,48,52,60]]])
print(ar5)
print(ar5.ndim)
print()
for i in np.nditer(ar5,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[23 34 45 56 67 78]
  [12 24 36 48 52 60]]]
3

b'23'
b'34'
b'45'
b'56'
b'67'
b'78'
b'12'
b'24'
b'36'
b'48'
b'52'
b'60'


In [33]:
ar6=np.array([[[23,34,45,56,67,78],[12,24,36,48,52,60]]])
print(ar6)
print(ar6.ndim)
print()
for i,d in np.ndenumerate(ar6):
    print(i,d)

[[[23 34 45 56 67 78]
  [12 24 36 48 52 60]]]
3

(0, 0, 0) 23
(0, 0, 1) 34
(0, 0, 2) 45
(0, 0, 3) 56
(0, 0, 4) 67
(0, 0, 5) 78
(0, 1, 0) 12
(0, 1, 1) 24
(0, 1, 2) 36
(0, 1, 3) 48
(0, 1, 4) 52
(0, 1, 5) 60
