# Joining Two arrays

To Join two arrays some functions are there.

There are:
    
a,b are the names of the arrays

axis = 0 for columns

axis = 1 for rows
    
1.concatenate((a,b),axis)

2.stack((a,b))

3.vstack((a,b)) - columns

4.hstack((a,b)) - row

5.dstack((a,b)) - depth o rheight

Jioning Array: Joining means putting contents of two or more arrays in a single array 3D array.

# Code:Joining two arrays

In [3]:
import numpy as np
a = np.array([34,35,36,37])
print(a)

[34 35 36 37]


In [4]:
import numpy as np
b = np.array([54,55,56,57])
print(b)

[54 55 56 57]


In [5]:
import numpy as np
c = np.arange(8).reshape(2,4)
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [6]:
d= np.arange(8,16).reshape(2,4)
print(d)

[[ 8  9 10 11]
 [12 13 14 15]]


In [10]:
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
y = np.array([[[11,12,13],[24,25,26]],[[37,38,39],[40,41,42]]])
print(y)

[[[11 12 13]
  [24 25 26]]

 [[37 38 39]
  [40 41 42]]]


# 1.concatenate():

In [5]:
e=np.concatenate((a,b))
print(e)

[34 35 36 37 54 55 56 57]


    or

In [6]:
f=np.concatenate((a,b),axis=0)
print(f)

[34 35 36 37 54 55 56 57]


# Possible Error:

In [7]:
g=np.concatenate((a,b),axis=1)
print(g)

AxisError: axis 1 is out of bounds for array of dimension 1

In [8]:
h=np.concatenate((c,d))
print(h)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [10]:
i=np.concatenate((c,d),axis = 0)
print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
j=np.concatenate((c,d),axis = 1)
print(j)

[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [17]:
k=np.concatenate((x,y))
print(k)

[[[11 12 13]
  [24 25 26]]

 [[37 38 39]
  [40 41 42]]

 [[11 12 13]
  [24 25 26]]

 [[37 38 39]
  [40 41 42]]]


In [18]:
l=np.concatenate((x,y),axis = 0)
print(l)

[[[11 12 13]
  [24 25 26]]

 [[37 38 39]
  [40 41 42]]

 [[11 12 13]
  [24 25 26]]

 [[37 38 39]
  [40 41 42]]]


In [19]:
m=np.concatenate((x,y),axis = 1)
print(m)

[[[11 12 13]
  [24 25 26]
  [11 12 13]
  [24 25 26]]

 [[37 38 39]
  [40 41 42]
  [37 38 39]
  [40 41 42]]]


# 2.stack():

In [23]:
n = np.stack((a,b))
print(n)

[[34 35 36 37]
 [54 55 56 57]]


In [24]:
o = np.stack((a,b),axis = 0)
print(o)

[[34 35 36 37]
 [54 55 56 57]]


In [26]:
p = np.stack((a,b),axis = 1)
print(p)

[[34 54]
 [35 55]
 [36 56]
 [37 57]]


In [29]:
q = np.stack((c,d))
print(q)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [30]:
r = np.stack((c,d))
print(r)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


      or

In [31]:
s = np.stack((c,d),axis=0)
print(s)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [32]:
t = np.stack((c,d),axis=1)
print(t)

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [37]:
u = np.stack((x,y))
print(u)

[[[[11 12 13]
   [24 25 26]]

  [[37 38 39]
   [40 41 42]]]


 [[[11 12 13]
   [24 25 26]]

  [[37 38 39]
   [40 41 42]]]]


In [38]:
v = np.stack((x,y),axis = 0)
print(v)

[[[[11 12 13]
   [24 25 26]]

  [[37 38 39]
   [40 41 42]]]


 [[[11 12 13]
   [24 25 26]]

  [[37 38 39]
   [40 41 42]]]]


In [39]:
w = np.stack((x,y),axis = 1)
print(w)

[[[[11 12 13]
   [24 25 26]]

  [[11 12 13]
   [24 25 26]]]


 [[[37 38 39]
   [40 41 42]]

  [[37 38 39]
   [40 41 42]]]]


# 3.hstack():

In [7]:
X = np.hstack((a,b))
print(X)

[34 35 36 37 54 55 56 57]


In [8]:
import numpy as np
A = np.hstack((c,d))
print(A)

[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [12]:
D = np.hstack((x,y))
print(D)

[[[ 1  2  3]
  [ 4  5  6]
  [11 12 13]
  [24 25 26]]

 [[ 7  8  9]
  [10 11 12]
  [37 38 39]
  [40 41 42]]]


# Possible Errors:

In [45]:
Y = np.hstack((a,b),axis = 0)
print(Y)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [46]:
Z = np.hstack((a,b),axis = 1)
print(Z)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [48]:
B = np.hstack((c,d),axis = 0)
print(B)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [49]:
C = np.hstack((c,d),axis = 1)
print(C)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [51]:
E = np.hstack((x,y),axis = 0)
print(E)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [52]:
F = np.hstack((c,d),axis = 1)
print(F)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

# 4.vstack():

In [53]:
G = np.vstack((a,b))
print(G)

[[34 35 36 37]
 [54 55 56 57]]


In [13]:
J = np.vstack((c,d))
print(J)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [14]:
M = np.vstack((x,y))
print(M)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[11 12 13]
  [24 25 26]]

 [[37 38 39]
  [40 41 42]]]


In [54]:
H = np.vstack((a,b),axis = 0)
print(H)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [55]:
I = np.vstack((a,b),axis = 1)
print(I)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [57]:
K = np.vstack((c,d),axis = 0)
print(K)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [58]:
L = np.vstack((c,d),axis = 1)
print(L)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [60]:
N = np.vstack((x,y),axis = 0)
print(N)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

In [61]:
O = np.vstack((x,y),axis = 1)
print(O)

TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'axis'

# 5.dstack():

In [62]:
P = np.dstack((a,b))
print(P)

[[[34 54]
  [35 55]
  [36 56]
  [37 57]]]


In [63]:
Q = np.dstack((c,d))
print(Q)

[[[ 0  8]
  [ 1  9]
  [ 2 10]
  [ 3 11]]

 [[ 4 12]
  [ 5 13]
  [ 6 14]
  [ 7 15]]]


In [64]:
R = np.dstack((x,y))
print(R)

[[[11 12 13 11 12 13]
  [24 25 26 24 25 26]]

 [[37 38 39 37 38 39]
  [40 41 42 40 41 42]]]


# Possible Error:

In [65]:
S = np.dstack((x,y),axis = 1)
print(S)

TypeError: _dstack_dispatcher() got an unexpected keyword argument 'axis'

# Splitting of an arrays

If we want to split the array into no:of divisions, we have to use some functions.
    
1. split(Array, no:of split)

    no:of splits - equal division
    
2. array_split(array,no:of splits)

3. hsplit()

4. vsplit() - Not applicable for ID array minimum of 2D Array is required to implement vsplit()

Split Array: Splitting breaks one array into multiple.

In [67]:
import numpy as np
p = np.arange(11)
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10]


# 1.split():

In [68]:
q = np.split(p,2)
print(q)

ValueError: array split does not result in an equal division

# 2.array_split():

In [69]:
r = np.array_split(p,2)
print(r)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [70]:
s = np.array_split(p,3)
print(s)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]


In [71]:
t = np.array_split(p,4)
print(t)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10])]


In [43]:
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [73]:
import numpy as np
ar_1 = np.array([12,14,16,18,20,22])
print(ar_1)
ar_2 = np.array_split(ar_1,3)
print()
print(ar_2)
print()
print(type(ar_2))

[12 14 16 18 20 22]

[array([12, 14]), array([16, 18]), array([20, 22])]

<class 'list'>


In [74]:
import numpy as np
ar_3 = np.array([[12,14,16,18,20,22],[21,45,68,97,63,10]])
print(ar_3)
ar_4 = np.array_split(ar_3,3)
print()
print(ar_4)
print()
print(type(ar_4))

[[12 14 16 18 20 22]
 [21 45 68 97 63 10]]

[array([[12, 14, 16, 18, 20, 22]]), array([[21, 45, 68, 97, 63, 10]]), array([], shape=(0, 6), dtype=int32)]

<class 'list'>


In [78]:
import numpy as np
ar_5 = np.array([[12,14,16,18,20,22],[21,45,68,97,63,10]])
print(ar_5)
ar_6 = np.array_split(ar_5,3,axis = 1)
print()
print(ar_6)
print()
print(type(ar_6))

[[12 14 16 18 20 22]
 [21 45 68 97 63 10]]

[array([[12, 14],
       [21, 45]]), array([[16, 18],
       [68, 97]]), array([[20, 22],
       [63, 10]])]

<class 'list'>


In [80]:
import numpy as np
ar_7 = np.array([[12,14,16,18,20,22],[21,45,68,97,63]])
print(ar_7)
ar_8 = np.array_split(ar_7,4)
print()
print(ar_8)
print()
print(type(ar_8))

[list([12, 14, 16, 18, 20, 22]) list([21, 45, 68, 97, 63])]

[array([list([12, 14, 16, 18, 20, 22])], dtype=object), array([list([21, 45, 68, 97, 63])], dtype=object), array([], dtype=object), array([], dtype=object)]

<class 'list'>


C:\Users\mouni\AppData\Local\Temp\ipykernel_25912\3730707689.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar_7 = np.array([[12,14,16,18,20,22],[21,45,68,97,63]])


# 3.hsplit():

In [15]:
v = np.arange(10)
w = np.hsplit(v,2)
print(w)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


# Possible Errors:

In [45]:
u = np.hsplit(p)
print(u)

TypeError: _hvdsplit_dispatcher() missing 1 required positional argument: 'indices_or_sections'

In [50]:
x = np.hsplit(p,2)
print(x)

ValueError: array split does not result in an equal division

# 4.vsplit():

In [16]:
arr = np.arange(12).reshape(6,2)
print(arr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [17]:
arr_1 = np.vsplit(arr,6)
print(arr_1)

[array([[0, 1]]), array([[2, 3]]), array([[4, 5]]), array([[6, 7]]), array([[8, 9]]), array([[10, 11]])]


# Possible Errors:

In [51]:
v = np.arange(10)
y = np.vsplit(v,2)
print(y)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [52]:
z = np.vsplit(p,2)
print(z)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [61]:
arr_2 = np.vsplit(arr,12)
print(arr_2)

ValueError: array split does not result in an equal division

In [62]:
arr_3 = np.vsplit(arr,5)
print(arr_3)

ValueError: array split does not result in an equal division

# Searching

How to search an element in an array?

Searching functions i.e., where() & searchsorted() returns always indicies.

1. where() - Retuns index of a given valu/ values



2. searchsorted() - Binarysearch i.e., It will be implemented Binary search.

* Return the index where the specified value should be inserted.

* Elements should be in sorted order.

* Search will be done individually.

# 1.where():

In [65]:
import numpy as np
a = np.arange(10,120,10)
b=np.where(a==30)
print(b)

(array([2], dtype=int64),)


In [66]:
import numpy as np
a = np.arange(10,120,10)
c=np.where(a==50)
print(c)

(array([4], dtype=int64),)


In [84]:
import numpy as np
a = np.arange(10,120,10)
y=np.where(a==80)
print(y)

(array([7], dtype=int64),)


In [85]:
import numpy as np
a = np.arange(10,120,10)
z=np.where(a==74)
print(z)

(array([], dtype=int64),)


In [67]:
import numpy as np
a = np.arange(10,120,10)
d=np.where(a%40 == 0)
print(d)

(array([3, 7], dtype=int64),)


In [68]:
import numpy as np
a = np.arange(10,120,10)
np.where(a%40 == 0)

(array([3, 7], dtype=int64),)

In [69]:
import numpy as np
a = np.arange(10,120,10)
d=np.where(a - 20 )
print(d)

(array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)


In [70]:
import numpy as np
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


# 2.searchsorted():

In [71]:
f = np.searchsorted(e,25)
print(f)

10


In [72]:
g = np.array([10,20,30,40,50,60,70,80,90])
print(g)

[10 20 30 40 50 60 70 80 90]


In [82]:
x = np.searchsorted(g,56)
print(x)

5


In [74]:
h = np.searchsorted(g,25)
print(h)

2


In [78]:
i = np.searchsorted(g,[54,65,76])
print(i)

[5 6 7]


In [81]:
j = np.searchsorted(g,[13,42,85,48,96,110,120])
print(j)

[1 4 8 4 9 9 9]


# sort()

sort() - quick sort

* sort() has Four Parameters

i. array

ii. axis - Bydefault axis = 1

iii. kind 

       quick - Bydefault
    
       Merge
        
iv. order

sort(array, axis,order)

# Code:sort()

In [13]:
import numpy as np
x = np.array([90,70,80,10,40,35,28])
print(x)

[90 70 80 10 40 35 28]


In [15]:
y = np.sort(x)
print(y)

[10 28 35 40 70 80 90]


In [17]:
z = np.sort(x,axis=0)
print(z)

[10 28 35 40 70 80 90]


# Possible Error:

In [18]:
p = np.sort(x,axis=1)
print(p)

AxisError: axis 1 is out of bounds for array of dimension 1

In [8]:
import numpy as np
a=np.array([[60,30,20],[10, 70, 40]])
print(a)

[[60 30 20]
 [10 70 40]]


In [9]:
b = np.sort(a,axis=0)
print(b)

[[10 30 20]
 [60 70 40]]


In [11]:
c = np.sort(a)
print(c)

[[20 30 60]
 [10 40 70]]


   or

In [12]:
d = np.sort(a,axis=1)
print(d)

[[20 30 60]
 [10 40 70]]


In [20]:
import numpy as np
e = np.array([[[20,80,40],[30, 50, 10]],[[56,78,34],[94,38,65]]])
print(e)

[[[20 80 40]
  [30 50 10]]

 [[56 78 34]
  [94 38 65]]]


In [22]:
f = np.sort(e)
print(f)

[[[20 40 80]
  [10 30 50]]

 [[34 56 78]
  [38 65 94]]]


In [23]:
g = np.sort(e,axis=1)
print(g)

[[[20 50 10]
  [30 80 40]]

 [[56 38 34]
  [94 78 65]]]


In [24]:
h = np.sort(e,axis=0)
print(h)

[[[20 78 34]
  [30 38 10]]

 [[56 80 40]
  [94 50 65]]]


# Possible Error:

In [26]:
i = np.sort(e,axis=1,order="F")
print(i)

ValueError: Cannot specify order when the array has no fields.

In [30]:
import numpy as np
d=np.dtype([('name','S10'),('perc',float)])
s=np.array([("abc",94.3),("def",85.6),("ghi",60.4)])
print(s)

[['abc' '94.3']
 ['def' '85.6']
 ['ghi' '60.4']]


In [36]:
S = np.array([("abc",90.3),("def",95.3),("ghi",65.4)],dtype=d)
t = np.sort(S,order="perc")
print(t)

[(b'ghi', 65.4) (b'abc', 90.3) (b'def', 95.3)]


# NumPy Array Functions: search(), sort(), search sorted(), Filter()

# 1. search():

Search an array for a certain value and return the indexes that get a match.

In [88]:
import numpy as np
array1 = np.array([2,4,6,8,10,12,14,16,2,5,6,8,2])
a = np.where(array1==2)
print(array1)
print(a)

[ 2  4  6  8 10 12 14 16  2  5  6  8  2]
(array([ 0,  8, 12], dtype=int64),)


In [90]:
import numpy as np
array1 = np.array([2,4,6,8,10,12,14,16,2,5,6,8,2,12,18,16,4,4,10])
a = np.where(array1==6)
print(array1)
print(a)

[ 2  4  6  8 10 12 14 16  2  5  6  8  2 12 18 16  4  4 10]
(array([ 2, 10], dtype=int64),)


In [91]:
import numpy as np
array2 = np.array([2,4,6,8,10,12,14,16,2,5,6,8,2,12,18,16,4,4,10])
b = np.where(array2/2==0)
print(array2)
print(b)

[ 2  4  6  8 10 12 14 16  2  5  6  8  2 12 18 16  4  4 10]
(array([], dtype=int64),)


In [93]:
import numpy as np
array3 = np.array([2,4,6,8,10,12,14,16,2,5,6,8,2,12,18,16,4,4,10])
c = np.where(array3%2==0)
print(array3)
print(c)

[ 2  4  6  8 10 12 14 16  2  5  6  8  2 12 18 16  4  4 10]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18], dtype=int64),)


In [95]:
import numpy as np
array4 = np.array([2,4,6,8,10,12,14,16,2,5,6,8,2,12,18,16,4,4,10])
d = np.where(array%2!=2)
print(array4)
print(d)

[ 2  4  6  8 10 12 14 16  2  5  6  8  2 12 18 16  4  4 10]
(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)


# 2. search sorted():

Which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order

In [97]:
import numpy as np
array5 = np.array([1,2,3,4,5,2,3,6,5,7,9,8,3,4,6,8,7,9,5,3,1,9,3,6,5])
array6 = np.searchsorted(array5,5)
print(array6)

23


In [99]:
import numpy as np
array7 = np.array([1,2,3,4,5,2,3,6,5,7,9,8,3,4,6,8,7,9,5,3,1,9,3,6,5])
array8 = np.searchsorted(array7,8)
print(array8)

25


In [100]:
import numpy as np
array9 = np.array([1,2,3,4,5,7,8])
array10 = np.searchsorted(array9,6)
print(array10)

5


In [105]:
import numpy as np
arra9= np.array([1,2,3,4,5,7,8])
arra10 = np.searchsorted(arra9,3,side = "right")
print(arra10)

3


In [107]:
import numpy as np
arra11= np.array([1,2,3,4,5,7,8])
arra12 = np.searchsorted(arra11,3)
print(arra12)

2


In [101]:
import numpy as np
array11 = np.array([1,2,3,4,5,7,8,14,16,19,25])
array12 = np.searchsorted(array11,10)
print(array12)

7


In [112]:
import numpy as np
arra11 = np.array([1,2,3,4,5,7,8,14,16,19,25])
arra12 = np.searchsorted(arra11,18,side = "right")
print(arra12)

9


In [102]:
import numpy as np
array13 = np.array([1,2,3,4,5,7,8,14,16,19,25])
array14 = np.searchsorted(array13,22)
print(array14)

10


In [113]:
import numpy as np
arra13 = np.array([1,2,3,4,5,7,8,14,16,19,25])
arra14 = np.searchsorted(arra13,22,side = "right")
print(arra14)

10


In [116]:
import numpy as np
array15 = np.array([1,2,3,4,7,8,14,16,19,25])
array16 = np.searchsorted(array15,[5,6,7,22],side = "right")
print(array16)

[4 4 5 9]


In [117]:
import numpy as np
array17 = np.array([1,2,3,4,8,14,16,19,25])
array18 = np.searchsorted(array17,[5,6,7],side = "right")
print(array18)

[4 4 4]


# 3. sort():

Ordered sequence is any sequence that has an order corresponding to elements,like numeric or alphabetical, ascending or descending.

In [119]:
import numpy as np
array19 = np.array([1,2,5,9,3,5,6,9,2,4,8,4])
print(array19)
array20 = np.sort(array19)
print(array20)

[1 2 5 9 3 5 6 9 2 4 8 4]
[1 2 2 3 4 4 5 5 6 8 9 9]


In [122]:
import numpy as np
array21 = np.array([1,2,5,9,3,5,6,9,2,4,8,4])
print(array21)
array22 = np.sort(array21,axis = 0)
print(array22)

[1 2 5 9 3 5 6 9 2 4 8 4]
[1 2 2 3 4 4 5 5 6 8 9 9]


# Possible Error:

In [123]:
import numpy as np
array23 = np.array([1,2,5,9,3,5,6,9,2,4,8,4])
print(array23)
array24 = np.sort(array23,axis = 1)
print(array24)

[1 2 5 9 3 5 6 9 2 4 8 4]


AxisError: axis 1 is out of bounds for array of dimension 1

In [125]:
import numpy as np
array25 = np.array([[2,1,5],[9,6,8],[3,7,4]])
print(array25)
array26 = np.sort(array25)
print(array26)

[[2 1 5]
 [9 6 8]
 [3 7 4]]
[[1 2 5]
 [6 8 9]
 [3 4 7]]


#  or

In [127]:
import numpy as np
array27 = np.array([[2,1,5],[9,6,8],[3,7,4]])
print(array27)
array28 = np.sort(array27,axis = 1)
print(array28)

[[2 1 5]
 [9 6 8]
 [3 7 4]]
[[1 2 5]
 [6 8 9]
 [3 4 7]]


In [128]:
import numpy as np
array29 = np.array([[2,1,5],[9,6,8],[3,7,4]])
print(array29)
array30 = np.sort(array29,axis = 0)
print(array30)

[[2 1 5]
 [9 6 8]
 [3 7 4]]
[[2 1 4]
 [3 6 5]
 [9 7 8]]


In [130]:
import numpy as np
array31 = np.array([[[2,1,5],[9,6,8]],[[3,7,4],[23,41,67]]])
print(array31)
array32 = np.sort(array31,axis = 1)
print(array32)

[[[ 2  1  5]
  [ 9  6  8]]

 [[ 3  7  4]
  [23 41 67]]]
[[[ 2  1  5]
  [ 9  6  8]]

 [[ 3  7  4]
  [23 41 67]]]


In [132]:
import numpy as np
array33 = np.array([[[2,1,5],[9,6,8]],[[3,7,4],[23,41,67]]])
print(array33)
array34 = np.sort(array33)
print(array34)

[[[ 2  1  5]
  [ 9  6  8]]

 [[ 3  7  4]
  [23 41 67]]]
[[[ 1  2  5]
  [ 6  8  9]]

 [[ 3  4  7]
  [23 41 67]]]


In [134]:
import numpy as np
array35 = np.array([[[2,1,5],[9,6,8]],[[3,7,4],[23,41,67]]])
print(array35)
array36 = np.sort(array35,axis = 0)
print(array36)

[[[ 2  1  5]
  [ 9  6  8]]

 [[ 3  7  4]
  [23 41 67]]]
[[[ 2  1  4]
  [ 9  6  8]]

 [[ 3  7  5]
  [23 41 67]]]


# 4. filter():

Filter array function: Getting some elements out of an existing array and creating a new array out of them.

In [136]:
array37 = np.array(["a","b","c","d","f","r","h"])
filter = [False, True, True, False, True, True, False]
array38 = array37[filter]
print(array38)
print()
print(type(array38))

['b' 'c' 'f' 'r']

<class 'numpy.ndarray'>
