# Axis

axis = 0 - for Column

axis = 1 - for Row

# axis = 0:

In [1]:
import numpy as np
a = np.array([[85,79,73],[65,32,74]])
print(a)

[[85 79 73]
 [65 32 74]]


In [2]:
b = np.sort(a,axis=0)
print(b)

[[65 32 73]
 [85 79 74]]


# axis = 1:

In [3]:
c = np.sort(a,axis=1)
print(c)

[[73 79 85]
 [32 65 74]]


# Datatypes:

i - int

f - float

s - string

u - unicode strings

m - timedelta

M - datetime

o - object

v - void

Attributes: datatype to represent datatype of an array.

dtype

ndim

shape

In [40]:
import numpy as np
t = np.array([12,13,14,15,16])
print(t)
print(t.dtype)

[12 13 14 15 16]
int32


In [41]:
u = np.array(['1','2','3','4','5'])
print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [42]:
v = np.array(['30','50','70','90','10'])
print(v)
print(v.dtype)

['30' '50' '70' '90' '10']
<U2


In [46]:
import numpy as np
w = np.array(['55','65','35','95','84'],dtype="U")
print(w)
print(w.dtype)

['55' '65' '35' '95' '84']
<U2


In [47]:
import numpy as np
x = np.array(['55','65','35','95','84'],dtype="i")
print(x)
print(x.dtype)

[55 65 35 95 84]
int32


# Possible Error:

In [48]:
import numpy as np
y = np.array(['a','20','40','60','80'],dtype="i")
print(y)
print(y.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [49]:
import numpy as np
z = np.array([38,58,98,78,18],dtype="i")
print(z)
print(z.dtype)

[38 58 98 78 18]
int32


         or

In [50]:
import numpy as np
a = np.array([38,58,98,78,18])
print(a)
print(a.dtype)

[38 58 98 78 18]
int32


In [51]:
import numpy as np
b = np.array([38,58,98,78,18],dtype="U")
print(b)
print(b.dtype)

['38' '58' '98' '78' '18']
<U2


In [4]:
import numpy as np
d = np.array([25,35,45,55,65,75])
print(d)

[25 35 45 55 65 75]


In [5]:
print(d.dtype)

int32


In [6]:
import numpy as array
e = np.array([20,30,40,50,60])
print(e)

[20 30 40 50 60]


In [7]:
import numpy as array
f = np.array([20,30,40,50,60],dtype = "f")
print(f)

[20. 30. 40. 50. 60.]


In [8]:
import numpy as array
g = np.array([20,30,40,50,60],dtype = "float")
print(g)

[20. 30. 40. 50. 60.]


In [9]:
import numpy as array
h = np.array([20,30,40,50,60])
print(h)

[20 30 40 50 60]


# List of characters that are used to represent dtype in numpy:
    Datatypes as Function

i - integer

b - boolean

u - unsighned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - String

U - unicode string

V - the fixed chunk of memory for the other types(void)

In [3]:
import numpy as np
g = np.array([56,45,87,93,12,91])
print(g)
print("Data Type:",g.dtype)

[56 45 87 93 12 91]
Data Type: int32


In [4]:
import numpy as np
h = np.array([56,45,87,93,12,91],dtype = np.int8)
print(h)
print("Data Type:",h.dtype)

[56 45 87 93 12 91]
Data Type: int8


In [5]:
import numpy as np
i = np.array([56,45,87,93,12,91],dtype = "f")
print(i)
print("Data Type:",i.dtype)

[56. 45. 87. 93. 12. 91.]
Data Type: float32


In [6]:
import numpy as np
j = np.array([23,67,54,12])
k = np.float32(j)
print("Datatype:",j.dtype)
print("Data Type:",k.dtype)

Datatype: int32
Data Type: float32


In [2]:
import numpy as np
l = np.array([23,67,54,12])
m = np.float32(l)
p = np.int_(m)
print("Datatype:",l.dtype)
print("Data Type:",m.dtype)
print("Data Type:",p.dtype)

Datatype: int32
Data Type: float32
Data Type: int32


In [3]:
q = np.array([23,56,74,97])
r = q.astype(float)
print(q)
print(r)

[23 56 74 97]
[23. 56. 74. 97.]


# astype():

In [10]:
x = h.astype("f")
print(x)

[20. 30. 40. 50. 60.]


In [11]:
i = x.astype("i")
print(i)

[20 30 40 50 60]


# Possible Error:

In [12]:
j = np.array(['a','20','30'])
k = j.astype("i")
print(k)

ValueError: invalid literal for int() with base 10: 'a'

In [13]:
l = np.array(['10','20','30','40','50'])
m = l.astype("i")
print(m)

[10 20 30 40 50]


In [31]:
import numpy as np
n = np.array([23,43,53,63,73,83])
print(n)

[23 43 53 63 73 83]


In [32]:
print(n.dtype)

int32


In [33]:
o = n.astype("f")
print(o)

[23. 43. 53. 63. 73. 83.]


In [34]:
print(o.dtype)

float32


In [35]:
import numpy as np
p = np.array([54,64,74,84,94])
print(p)
print(p.dtype)
q = p.astype("bool")
print(q)
print(q.dtype)

[54 64 74 84 94]
int32
[ True  True  True  True  True]
bool


In [39]:
import numpy as np
r = np.array([20,0,40,0,60])
print(r)
print(r.dtype)
s = r.astype("bool")
print(s)
print(s.dtype)

[20  0 40  0 60]
int32
[ True False  True False  True]
bool


# copy() and view():

copy():
    
1. External copy

2. If any one element is modified then it will not reflect to another.

3. Two arrays

copy():
    
1.The copy owns the data.

2. The copy of an array is a new array.

3. The changes made in the copy data does not reflect in the original array.

view():
    
1.Create a reference to existing array.

2. If any one element is modified then it will be reflected on original array.

3. Only one array.

view():
    
1. The view does not own the data.

2. A view of the original array.

3. any changes made to the view will affect the original array and any changes made to the original array will affect the view.

# Code: copy() and view()

In [14]:
import numpy as np
m = np.array([10,20,30,40,50])
print(m)

[10 20 30 40 50]


In [15]:
c = m.copy()
print(c)

[10 20 30 40 50]


In [16]:
v = m.view()
print(v)

[10 20 30 40 50]


In [17]:
c[1]=70

In [18]:
print(c)

[10 70 30 40 50]


In [19]:
print(m)

[10 20 30 40 50]


In [20]:
v[2]=70

In [21]:
print(v)

[10 20 70 40 50]


In [22]:
print(m)

[10 20 70 40 50]


In [23]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [24]:
c=a.copy()
print("copy",c)

copy [10 20 30 40 50]


In [25]:
c[1]=100
print("a=",a,"c=",c)

a= [10 20 30 40 50] c= [ 10 100  30  40  50]


In [28]:
v = a.view()
print("VIEW=",v)

VIEW= [ 10 100  30  40  50]


In [29]:
v[1] = 100
print("a=",a,"v=",v)

a= [ 10 100  30  40  50] v= [ 10 100  30  40  50]


In [30]:
v=a.view()
print("VIEW=",v)
v[1]=100
v[2]=200
print("a=",a,"v=",v)
print("c=",c.base)
print("v=",v.base)

VIEW= [ 10 100  30  40  50]
a= [ 10 100 200  40  50] v= [ 10 100 200  40  50]
c= None
v= [ 10 100 200  40  50]


In [3]:
import numpy as np
arr_1 = np.array([45,68,93,52,74])
print(arr_1)
copy = arr_1.copy()
print(copy)
arr_1[1] = 86
print("array:", arr_1)
print("copy:", copy)

[45 68 93 52 74]
[45 68 93 52 74]
array: [45 86 93 52 74]
copy: [45 68 93 52 74]


In [4]:
import numpy as np
arr_2 = np.array([45,68,93,52,74])
print(arr_2)
view = arr_2.view()
print(view)
arr_2[2] = 35
print("array:", arr_2)
print("copy:", view)

[45 68 93 52 74]
[45 68 93 52 74]
array: [45 68 35 52 74]
copy: [45 68 35 52 74]


# Arithmetic Functions

1. shuffle()

2. unique()

3. resize()

4. flatten()

5. Ravel()

# 1. shuffle():

In [8]:
import numpy as np
arr_3 = np.array([3,5,7,9,1])
arr_4 = np.random.shuffle(arr_3)
print(arr_4)
print(arr_3)

None
[5 1 7 9 3]


In [9]:
import numpy as np
arr_3 = np.array([3,5,7,9,1])
arr_4 = np.random.shuffle(arr_3)
print(arr_4)
print(arr_3)

None
[5 1 9 7 3]


In [10]:
import numpy as np
arr_3 = np.array([3,5,7,9,1])
arr_4 = np.random.shuffle(arr_3)
print(arr_4)
print(arr_3)

None
[1 5 3 9 7]


# 2. unique():

In [11]:
import numpy as np
arr_5 = np.array([2,3,5,4,1,8,6,7,9,2,5,3,6,4,8,4,9,2])
arr_6 = np.unique(arr_5)
print(arr_6)

[1 2 3 4 5 6 7 8 9]


In [71]:
import numpy as np
arr_30 = np.array([2,3,5,4,1,8,6,7,9,2,5,3,6,4,8,4,9,2])
arr_31 = np.unique(arr_30,return_index = True, return_counts =True)
print(arr_31)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([4, 0, 1, 3, 2, 6, 7, 5, 8], dtype=int64), array([1, 3, 2, 3, 2, 2, 1, 2, 2], dtype=int64))


# 3. resize():

In [12]:
import numpy as np
arr_7 = np.array([1,3,5,7,9,4])
arr_8 = np.resize(arr_7,(3,2))
print(arr_8)

[[1 3]
 [5 7]
 [9 4]]


In [14]:
import numpy as np
arr_9 = np.array([1,3,5,7,9,4])
arr_10 = np.resize(arr_9,(2,3))
print(arr_10)

[[1 3 5]
 [7 9 4]]


In [17]:
import numpy as np
arr_11 = np.array([1,3,5,7,9,4,2,8,6])
arr_12 = np.resize(arr_11,(2,3))
print(arr_12)

[[1 3 5]
 [7 9 4]]


In [18]:
import numpy as np
arr_12 = np.array([1,3,5,7,9,4,2,8,6])
arr_13 = np.resize(arr_12,(3,3))
print(arr_13)

[[1 3 5]
 [7 9 4]
 [2 8 6]]


# 4. Flatten():

** order:{'c','F','A','K'} - optional
    
** 'C' means to flatten in row-major(C-style)order.

** 'F' means to flatten in column-major(Fortran-style)order

** 'A' means to flatten in column-major order.

** if 'a' is Fortran*contiguous* in memory, row-major order otherwise.

** 'k' means to flatten 'a' in the order the elements occur in memory.

** The default is 'c'.

In [21]:
import numpy as np
arr_14 = np.array([5,8,9,6,2,1,3,7])
arr_15 = np.resize(arr_14,(4,2))
print(arr_15)
print()
print(arr_15.flatten())

[[5 8]
 [9 6]
 [2 1]
 [3 7]]

[5 8 9 6 2 1 3 7]


In [22]:
import numpy as np
arr_16 = np.array([5,8,9,6,2,1,3,7])
arr_17 = np.resize(arr_16,(2,4))
print(arr_17)
print()
print(arr_17.flatten())

[[5 8 9 6]
 [2 1 3 7]]

[5 8 9 6 2 1 3 7]


#   or

In [24]:
import numpy as np
arr_18 = np.array([5,8,9,6,2,1,3,7])
arr_19 = np.resize(arr_18,(2,4))
print(arr_19)
print()
print(arr_19.flatten(order="C"))

[[5 8 9 6]
 [2 1 3 7]]

[5 8 9 6 2 1 3 7]


In [25]:
import numpy as np
arr_20 = np.array([5,8,9,6,2,1,3,7])
arr_21 = np.resize(arr_20,(2,4))
print(arr_21)
print()
print(arr_21.flatten(order="F"))

[[5 8 9 6]
 [2 1 3 7]]

[5 2 8 1 9 3 6 7]


# 5. ravel():

In [40]:
import numpy as np
arr_20 = np.array([5,8,9,6,2,1,3,7])
arr_21 = np.resize(arr_20,(2,4))
print(arr_21)
print()
a = arr_21.flatten(order="F")
print(a)
print()
arr_22 = np.ravel(arr_21)
print("Ravel:",arr_22)

[[5 8 9 6]
 [2 1 3 7]]

[5 2 8 1 9 3 6 7]

Ravel: [5 8 9 6 2 1 3 7]


In [43]:
import numpy as np
arr_23 = np.array([5,8,9,6,2,1,3,7])
arr_24 = np.resize(arr_23,(2,4))
print(arr_24)
print()
b = arr_24.flatten()
print(a)
print()
arr_25 = np.ravel(arr_24)
print("Ravel:",arr_25)

[[5 8 9 6]
 [2 1 3 7]]

[5 2 8 1 9 3 6 7]

Ravel: [5 8 9 6 2 1 3 7]


In [44]:
import numpy as np
arr_26 = np.array([1,2,3,4,5,6])
arr_27 = np.resize(arr_26,(3,2))
print(arr_27)
print()
print("Flatten:",arr_27.flatten(order = "F"))
print("Ravel:",np.ravel(arr_27,order = "A"))

[[1 2]
 [3 4]
 [5 6]]

Flatten: [1 3 5 2 4 6]
Ravel: [1 2 3 4 5 6]


# NumPy array functions: Insert() and Delete Function

# insert():

insert function has three parametes.
    
    Syntax:
        
insert(Array_Name, Index position, value to be inserted)

In [45]:
import numpy as np
var = np.array([2,6,9,4,1,5])
print(var)
print()
print(type(var))
print()
i = np.insert(var,3,12)
print(i)

[2 6 9 4 1 5]

<class 'numpy.ndarray'>

[ 2  6  9 12  4  1  5]


In [46]:
import numpy as np
var1 = np.array([2,6,9,4,1,5])
print(var1)
print()
print(type(var1))
print()
j = np.insert(var1,(1,4),12)
print(j)

[2 6 9 4 1 5]

<class 'numpy.ndarray'>

[ 2 12  6  9  4 12  1  5]


In [47]:
import numpy as np
var2 = np.array([2,6,9,4,1,5])
print(var2)
print()
print(type(var2))
print()
k = np.insert(var2,(1,4),11.6)
print(k)

[2 6 9 4 1 5]

<class 'numpy.ndarray'>

[ 2 11  6  9  4 11  1  5]


In [48]:
import numpy as np
var3 = np.array([[2,6,9],[3,5,7]])
print(var3)
print()
print(type(var3))
print()
l = np.insert(var3,(1),11.6)
print(l)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[ 2 11  6  9  3  5  7]


In [66]:
import numpy as np
var4 = np.array([[2,6,9],[3,5,7]])
print(var4)
print()
print(type(var4))
print()
m = np.insert(var4,1,3,1)
print(m)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[[2 3 6 9]
 [3 3 5 7]]


In [67]:
import numpy as np
var5 = np.array([[2,6,9],[3,5,7]])
print(var5)
print()
print(type(var5))
print()
n = np.insert(var5,0,4,axis=1)
print(n)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[[4 2 6 9]
 [4 3 5 7]]


In [68]:
import numpy as np
var6 = np.array([[2,6,9],[3,5,7]])
print(var6)
print()
print(type(var6))
print()
p = np.insert(var6,0,4, axis=0)
print(p)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[[4 4 4]
 [2 6 9]
 [3 5 7]]


In [69]:
import numpy as np
var7= np.array([[2,6,9],[3,5,7]])
print(var7)
print()
print(type(var7))
print()
q = np.insert(var7,2,9, axis=0)
print(q)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[[2 6 9]
 [3 5 7]
 [9 9 9]]


In [70]:
import numpy as np
var8 = np.array([[2,6,9],[3,5,7]])
print(var8)
print()
print(type(var8))
print()
r = np.insert(var8,2,9, axis=1)
print(r)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[[2 6 9 9]
 [3 5 9 7]]


In [88]:
import numpy as np
var13 = np.array([[2,6,9],[3,5,7]])
print(var13)
print()
print(type(var13))
print()
s = np.insert(var13,2,[12,13], axis=1)
print(s)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[[ 2  6 12  9]
 [ 3  5 13  7]]


In [89]:
import numpy as np
var14 = np.array([[2,6,9],[3,5,7]])
print(var14)
print()
print(type(var14))
print()
t = np.insert(var14,2,[12,13,14], axis=0)
print(t)

[[2 6 9]
 [3 5 7]]

<class 'numpy.ndarray'>

[[ 2  6  9]
 [ 3  5  7]
 [12 13 14]]


# delete():

In [79]:
import numpy as np
var9 = np.array([3,5,7,9,1])
print(var9)
print()
print(var9.dtype)
print()
print(type(var9))
print()
i = np.insert(var9,3,90.8)
print(i)
print()
a = np.append(var9,90.8)
print(a)
print()
d = np.delete(var9,3)
print(d)
print()
print(var9)

[3 5 7 9 1]

int32

<class 'numpy.ndarray'>

[ 3  5  7 90  9  1]

[ 3.   5.   7.   9.   1.  90.8]

[3 5 7 1]

[3 5 7 9 1]


In [83]:
import numpy as np
var10 = np.array([[3,5,7,9],[1,2,4,6]])
print(var10)
print()
print(var10.dtype)
print()
print(type(var10))
print()
i1 = np.insert(var10,2,[45,67,89,12],axis = 0)
print(i1)
print()
a1 = np.append(var10,[[93,82,63,55]],axis=0)
print(a1)

[[3 5 7 9]
 [1 2 4 6]]

int32

<class 'numpy.ndarray'>

[[ 3  5  7  9]
 [ 1  2  4  6]
 [45 67 89 12]]

[[ 3  5  7  9]
 [ 1  2  4  6]
 [93 82 63 55]]
