# Arithmetic Operations

1. Addition

2. Subtraction

3. Multiplication

4. Division

5. Modulo

6. Power

7. Reciprocal

8. Complex

# Rules for implementing Arithmetic OPerations:

1. Shapes of Two arrays must be equal.

      numpy.shape(a)


2. Second array should have atleast one dimension and the no: of elements in that dimension should be equal to first array.
    
      a = (3,3)

      b = (3,) -possible

      b = (2,2) -not possible


3. Second array having single element.

# Rule-1:

Element to element

 x = [5,6],[8,9] -(2,2)=>shape of this array

 y = [4,3],[1,6] -(2,2)=>shape of this array

# Rule-2:

m = [2,6],[8,4] -(2,2)

n = [7,3] - (2,)

   or
    
n = [7,3],[7,3] -(2,2)    - rule-2:Possible



a = [3,9],[2,4] -(2,2)

b = [8,9,2] -(3,)        - rule-2:Not Possible

# Rule-3:

p = [3,2],[5,8]

q = 9

     or

q = [9,9],[9,9]   -Rule-3:Possible

# Built-In functions for Arithmetic Operations in NumPy

Addition - np.add(first_array, second_array)

Subtraction - np.subtract(a,b)

Multiplication - np.multiply(a,b)

Division - np.divide(a,b)

Modulo - np.mod(a,b) - b is a value

Power - np.power(a,b)

np.real(array)/np.imag(array)/np.conjugate(array)

In [2]:
import numpy as np
a = np.array([[3,6,9],[2,4,6],[1,5,7]])
b = np.array([[3,3,3],[3,3,3],[3,3,3]])
c = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(a,b)
print(a,c)

[[3 6 9]
 [2 4 6]
 [1 5 7]] [[3 3 3]
 [3 3 3]
 [3 3 3]]
[[3 6 9]
 [2 4 6]
 [1 5 7]] [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
print(a)

[[3 6 9]
 [2 4 6]
 [1 5 7]]


In [4]:
print(b)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [5]:
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
np.shape(a)

(3, 3)

In [7]:
np.shape(b)

(3, 3)

In [8]:
np.shape(c)

(3, 3)

In [9]:
d = np.array([25,45,65])
print(d)

[25 45 65]


In [10]:
np.shape(d)

(3,)

In [11]:
f = np.array([15,25])
print(f)

[15 25]


In [12]:
np.shape(f)

(2,)

In [13]:
np.add(a,b)

array([[ 6,  9, 12],
       [ 5,  7,  9],
       [ 4,  8, 10]])

In [14]:
np.add(a,c)

array([[ 4,  7, 10],
       [ 3,  5,  7],
       [ 2,  6,  8]])

In [15]:
g = np.array([10])
print(g)

[10]


In [16]:
np.shape(g)

(1,)

In [17]:
np.add(a,g)

array([[13, 16, 19],
       [12, 14, 16],
       [11, 15, 17]])

In [18]:
np.subtract(a,g)

array([[-7, -4, -1],
       [-8, -6, -4],
       [-9, -5, -3]])

In [19]:
np.multiply(a,g)

array([[30, 60, 90],
       [20, 40, 60],
       [10, 50, 70]])

In [20]:
np.divide(a,g)

array([[0.3, 0.6, 0.9],
       [0.2, 0.4, 0.6],
       [0.1, 0.5, 0.7]])

In [21]:
np.power(a,d)

array([[1180052131,          0, -558216695],
       [  33554432,          0,          0],
       [         1, 1157650709, 1159739911]], dtype=int32)

In [22]:
np.power(a,c)

array([[3, 6, 9],
       [2, 4, 6],
       [1, 5, 7]], dtype=int32)

# Possible Errors:

In [23]:
np.add(a,f)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [24]:
np.add(b,f)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [25]:
np.subtract(b,f)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [26]:
np.multiply(b,f)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [27]:
np.divide(b,f)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [28]:
np.power(b,f)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [29]:
np.power(b,g)

array([[59049, 59049, 59049],
       [59049, 59049, 59049],
       [59049, 59049, 59049]], dtype=int32)

In [30]:
np.mod(a,34)

array([[3, 6, 9],
       [2, 4, 6],
       [1, 5, 7]], dtype=int32)

In [48]:
np.mod(b,20)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [49]:
np.mod(f,30)

array([15, 25], dtype=int32)

In [50]:
np.mod(g,10)

array([0], dtype=int32)

In [57]:
np.mod(c,10)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [52]:
np.reciprocal(a)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0]], dtype=int32)

In [53]:
np.reciprocal(b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [54]:
np.reciprocal(f)

array([0, 0], dtype=int32)

In [55]:
np.reciprocal(g)

array([0], dtype=int32)

In [56]:
np.reciprocal(c)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [60]:
h = np.array([2,0.4,0.6,0.8,1.0])
np.reciprocal(h)

array([0.5       , 2.5       , 1.66666667, 1.25      , 1.        ])

In [63]:
complex_num = np.array([5+6j, 10-5j, 9+7j])
print(complex_num)

[ 5.+6.j 10.-5.j  9.+7.j]


In [64]:
np.real(complex_num)

array([ 5., 10.,  9.])

In [65]:
np.imag(complex_num)

array([ 6., -5.,  7.])

In [66]:
np.conjugate(complex_num)

array([ 5.-6.j, 10.+5.j,  9.-7.j])

In [68]:
print(complex_num)

[ 5.+6.j 10.-5.j  9.+7.j]


In [13]:
import numpy as np
arr_1 = np.array([2,4,6,8,12,14])
arr_2 = np.array([18,16,19,23,25,28])
arr_3 = np.arange(6).reshape(3,2)
arr_4 = np.arange(6,12).reshape(2,3)
print(arr_3)
print()
print(arr_4)
print()
print(arr_1.dot(arr_2)) 
print()
print(arr_3.dot(arr_4))
print()


[[0 1]
 [2 3]
 [4 5]]

[[ 6  7  8]
 [ 9 10 11]]

1090

[[ 9 10 11]
 [39 44 49]
 [69 78 87]]



In [1]:
import numpy as np
arr_1 = np.array([2,4,6,8,12,14])
arr_2 = np.array([18,16,19,23,25,28])

In [2]:
arr_1 - arr_2

array([-16, -12, -13, -15, -13, -14])

In [3]:
arr_1 * arr_2

array([ 36,  64, 114, 184, 300, 392])

In [4]:
arr_1 * 2

array([ 4,  8, 12, 16, 24, 28])

In [6]:
arr_1 > 2

array([False,  True,  True,  True,  True,  True])

In [7]:
arr_2 > 3

array([ True,  True,  True,  True,  True,  True])

In [9]:
arr_1 < 4

array([ True, False, False, False, False, False])

In [10]:
arr_2 < 3

array([False, False, False, False, False, False])

# Statistical Operations

1. amin() - minimum element

     axis = 0
    
     axis = 1
        
     complete array


2. amax() - maximum element

     axis = 0
    
     axis = 1
        
     complete array


3. average() - Average
  
    complete array
    
    weightedaverage


4. mean() - mean

    
5. median() - median


6. var() - variance


7. std() - Standard deviation

In [32]:
import numpy as np
x = np.array([[30,60,90],[10,20,40],[50,70,80]])
print(x)

[[30 60 90]
 [10 20 40]
 [50 70 80]]


In [71]:
np.amin(x)

10

In [73]:
np.amin(x,axis=1)

array([30, 10, 50])

In [74]:
np.amin(x,axis=0)

array([10, 20, 40])

In [75]:
np.amax(x)

90

In [77]:
np.amax(x,axis=1)

array([90, 40, 80])

In [78]:
np.amax(x,axis=0)

array([50, 70, 90])

In [79]:
np.average(x)

50.0

In [34]:
w = np.array([12,13,14])
print(w)

[12 13 14]


# Possible Error:

In [35]:
np.average(x,weights=w)

TypeError: Axis must be specified when shapes of a and weights differ.

In [82]:
np.average(x,weights=w,axis=0)

array([30.51282051, 50.25641026, 69.74358974])

In [88]:
np.average(x,weights=w,axis=1)

array([61.53846154, 24.1025641 , 67.43589744])

In [84]:
w1 = np.array([1,2,3])
print(w1)

[1 2 3]


In [86]:
np.average(x,weights=w1,axis=0)

array([33.33333333, 51.66666667, 68.33333333])

In [87]:
np.average(x,weights=w1,axis=1)

array([70.        , 28.33333333, 71.66666667])

In [89]:
np.mean(x)

50.0

In [90]:
np.mean(x,axis=0)

array([30., 50., 70.])

In [91]:
np.mean(x,axis=1)

array([60.        , 23.33333333, 66.66666667])

In [92]:
np.median(x)

50.0

In [93]:
np.median(x,axis=0)

array([30., 60., 80.])

In [94]:
np.median(x,axis=1)

array([60., 20., 70.])

In [95]:
np.var(x)

666.6666666666666

In [96]:
np.std(x)

25.81988897471611